import NextUiProvider from "./providers";
import { AuthProvider } from "./authProvider";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sameday-calculations",
  description: "Generated by create next app",
  icon: "/vercel.svg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUiProvider>
          <AuthProvider>
            <Navigation />
            {children}
          </AuthProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
